[package]
name = "stravant/roblox-gapfill"
version = "2.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "stravant/goodsignal@0.3.0"
React = "jsdotlua/react@17.1.0"
ReactRoblox = "jsdotlua/react-roblox@17.1.0"
Geometry = "stravant/geometry@0.1.3"
createSharedToolbar = "stravant/create-shared-toolbar@0.1.0"
DraggerHandler = "stravant/dragger-handler@0.1.3"